name: escpos_printer_workspace
description: "Workspace do projeto escpos_printer (monorepo federado)."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  escpos_printer:
    path: packages/escpos_printer
  escpos_printer_platform_interface:
    path: packages/escpos_printer_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
