name: escpos_printer
description: Flutter library/plugin for ESC/POS thermal printing with Wi-Fi, USB and Bluetooth transports.
version: 0.0.2
publish_to: none
homepage:

environment:
  sdk: ^3.10.8
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  escpos_printer_platform_interface:
    path: ../escpos_printer_platform_interface
  escpos_printer_android:
    path: ../escpos_printer_android
  escpos_printer_linux:
    path: ../escpos_printer_linux
  escpos_printer_macos:
    path: ../escpos_printer_macos
  escpos_printer_windows:
    path: ../escpos_printer_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: escpos_printer_android
      linux:
        default_package: escpos_printer_linux
      macos:
        default_package: escpos_printer_macos
      windows:
        default_package: escpos_printer_windows
